/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import modelo.TextPrompt;

/**
 *
 * @author anthony.ricse
 */
public class Ingrediente extends javax.swing.JPanel {

    /**
     * Creates new form pan
     */
 
    public Ingrediente() {
        initComponents();
         TextPrompt txt1Pane2 = new TextPrompt("Nombre", jTextField1);
        TextPrompt txt2Pane2 = new TextPrompt("Cantidad", jTextField2);
         TextPrompt txtPan3Nombre = new TextPrompt("Nombre", Txtfieldpan3Nombre);
        TextPrompt txtPan3Cantidad = new TextPrompt("Cantidad", TxtfieldPan3Cantidad);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        TablaIngrediente = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnMinus = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        BtnNewIngredient = new java.awt.Button();
        PanelOrden = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        btnAdd1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        btnMinus1 = new javax.swing.JButton();
        Txtfieldpan3Nombre = new javax.swing.JTextField();
        TxtfieldPan3Cantidad = new javax.swing.JTextField();
        BtnNewIngredient1 = new java.awt.Button();
        PanelOrden1 = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(950, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaIngrediente.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        TablaIngrediente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TablaIngrediente.setDoubleBuffered(true);
        TablaIngrediente.setName(""); // NOI18N

        jPanel1.setBackground(new java.awt.Color(180, 237, 131));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 140, 30));

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        btnAdd.setBorder(null);
        btnAdd.setContentAreaFilled(false);
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 30, 30));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 370));

        btnMinus.setBackground(new java.awt.Color(180, 237, 131));
        btnMinus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/restar.png"))); // NOI18N
        btnMinus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinus.setMinimumSize(new java.awt.Dimension(61, 30));
        btnMinus.setPreferredSize(new java.awt.Dimension(61, 30));
        jPanel1.add(btnMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 30, 30));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 130, 30));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 130, 30));

        BtnNewIngredient.setLabel("Agregar");
        BtnNewIngredient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNewIngredientActionPerformed(evt);
            }
        });
        jPanel1.add(BtnNewIngredient, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 130, -1));
        BtnNewIngredient.getAccessibleContext().setAccessibleName("Agregar");

        PanelOrden.setBackground(new java.awt.Color(102, 153, 255));
        PanelOrden.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jRadioButton1.setBackground(new java.awt.Color(102, 153, 255));
        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Ordenar Alfabetcamente");
        PanelOrden.add(jRadioButton1);

        jRadioButton2.setBackground(new java.awt.Color(102, 153, 255));
        jRadioButton2.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Ordenar por la cantidad");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        PanelOrden.add(jRadioButton2);

        jPanel1.add(PanelOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 150, 60));

        TablaIngrediente.addTab("", jPanel1);

        jPanel3.setBackground(new java.awt.Color(180, 237, 131));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 140, 30));

        btnAdd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        btnAdd1.setBorder(null);
        btnAdd1.setContentAreaFilled(false);
        btnAdd1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 30, 30));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 370));

        btnMinus1.setBackground(new java.awt.Color(180, 237, 131));
        btnMinus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/restar.png"))); // NOI18N
        btnMinus1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinus1.setMinimumSize(new java.awt.Dimension(61, 30));
        btnMinus1.setPreferredSize(new java.awt.Dimension(61, 30));
        jPanel3.add(btnMinus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 30, 30));

        Txtfieldpan3Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txtfieldpan3NombreActionPerformed(evt);
            }
        });
        jPanel3.add(Txtfieldpan3Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 130, 30));
        jPanel3.add(TxtfieldPan3Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 130, 30));

        BtnNewIngredient1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnNewIngredient1.setLabel("Agregar");
        BtnNewIngredient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNewIngredient1ActionPerformed(evt);
            }
        });
        jPanel3.add(BtnNewIngredient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 130, -1));

        PanelOrden1.setBackground(new java.awt.Color(102, 153, 255));
        PanelOrden1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jRadioButton3.setBackground(new java.awt.Color(102, 153, 255));
        jRadioButton3.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Ordenar Alfabetcamente");
        PanelOrden1.add(jRadioButton3);

        jRadioButton4.setBackground(new java.awt.Color(102, 153, 255));
        jRadioButton4.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("Ordenar por la cantidad");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        PanelOrden1.add(jRadioButton4);

        jPanel3.add(PanelOrden1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 150, 60));

        TablaIngrediente.addTab("", jPanel3);

        add(TablaIngrediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 840, 400));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salirBtn2.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 40, 50, 40));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoIngre.jpg"))); // NOI18N
        add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void BtnNewIngredientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNewIngredientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnNewIngredientActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
    
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void Txtfieldpan3NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txtfieldpan3NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txtfieldpan3NombreActionPerformed

    private void BtnNewIngredient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNewIngredient1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnNewIngredient1ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
System.exit(0);    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button BtnNewIngredient;
    private java.awt.Button BtnNewIngredient1;
    private javax.swing.JPanel PanelOrden;
    private javax.swing.JPanel PanelOrden1;
    public javax.swing.JTabbedPane TablaIngrediente;
    private javax.swing.JTextField TxtfieldPan3Cantidad;
    private javax.swing.JTextField Txtfieldpan3Nombre;
    public javax.swing.JButton btnAdd;
    public javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMinus1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables
}
