/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author anthony.ricse
 */
public class IngredientesFrm extends javax.swing.JFrame {

    /**
     * Creates new form IngredientesFrm
     */
    public IngredientesFrm() {
        initComponents();
        setLocationRelativeTo(null);
    }
     public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("image/logo.png"));
        return retValue;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCarne = new java.awt.Button();
        btnVerdura = new java.awt.Button();
        cardOpcion = new javax.swing.JPanel();
        panCarnes = new javax.swing.JPanel();
        lblFondoCarne = new javax.swing.JLabel();
        panVerdura = new javax.swing.JPanel();
        lblFondVerdura = new javax.swing.JLabel();
        btnRetroceder = new javax.swing.JButton();
        lblFondoIngre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(950, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCarne.setBackground(new java.awt.Color(130, 193, 89));
        btnCarne.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCarne.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        btnCarne.setForeground(new java.awt.Color(255, 255, 255));
        btnCarne.setLabel("Carnes");
        btnCarne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarneActionPerformed(evt);
            }
        });
        getContentPane().add(btnCarne, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 100, 30));

        btnVerdura.setBackground(new java.awt.Color(130, 193, 89));
        btnVerdura.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        btnVerdura.setForeground(new java.awt.Color(255, 255, 255));
        btnVerdura.setLabel("Verduras");
        btnVerdura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerduraActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerdura, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 100, 30));

        cardOpcion.setLayout(new java.awt.CardLayout());

        panCarnes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFondoCarne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/carnePrueba.png"))); // NOI18N
        panCarnes.add(lblFondoCarne, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 430));

        cardOpcion.add(panCarnes, "card2");

        panVerdura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFondVerdura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/VerduraPrueba.png"))); // NOI18N
        panVerdura.add(lblFondVerdura, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 440));

        cardOpcion.add(panVerdura, "card3");

        getContentPane().add(cardOpcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 830, 430));

        btnRetroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/salirBtn2.png"))); // NOI18N
        btnRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederActionPerformed(evt);
            }
        });
        getContentPane().add(btnRetroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 50, 50));

        lblFondoIngre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/FondoIngre.jpg"))); // NOI18N
        getContentPane().add(lblFondoIngre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarneActionPerformed
        cardOpcion.removeAll();
        cardOpcion.add(panCarnes);
        cardOpcion.repaint();
        cardOpcion.revalidate();
    }//GEN-LAST:event_btnCarneActionPerformed

    private void btnVerduraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerduraActionPerformed
        cardOpcion.removeAll();
        cardOpcion.add(panVerdura);
        cardOpcion.repaint();
        cardOpcion.revalidate();
    }//GEN-LAST:event_btnVerduraActionPerformed

    private void btnRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederActionPerformed
        principalFrm main = new principalFrm();
        main.dispose();
        main.setVisible(true);
        main.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnRetrocederActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngredientesFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngredientesFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngredientesFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngredientesFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngredientesFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnCarne;
    private javax.swing.JButton btnRetroceder;
    private java.awt.Button btnVerdura;
    private javax.swing.JPanel cardOpcion;
    private javax.swing.JLabel lblFondVerdura;
    private javax.swing.JLabel lblFondoCarne;
    private javax.swing.JLabel lblFondoIngre;
    private javax.swing.JPanel panCarnes;
    private javax.swing.JPanel panVerdura;
    // End of variables declaration//GEN-END:variables
}
