/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Carlos
 */
public class menuFrm extends javax.swing.JPanel {

    /**
     * Creates new form menuFrm
     */
    public menuFrm() {
         initComponents();
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblFoodMenu1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnFoodMenu1 = new javax.swing.JButton();
        lblFoodMenu2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnFoodMenu2 = new javax.swing.JButton();
        lblFoodMenu3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnFoodMenu3 = new javax.swing.JButton();
        lblFoodMenu4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnFoodMenu4 = new javax.swing.JButton();
        lblFoodMenu5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnFoodMenu5 = new javax.swing.JButton();
        lblFoodMenu6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnFoodMenu6 = new javax.swing.JButton();
        lblFoodMenu7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnFoodMenu7 = new javax.swing.JButton();
        lblFoodMenu8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnFoodMenu8 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblEDNI1 = new javax.swing.JLabel();
        cboxEEstado1 = new javax.swing.JCheckBox();
        lblENomComida1 = new javax.swing.JLabel();
        lblEDNI2 = new javax.swing.JLabel();
        lblENomComida2 = new javax.swing.JLabel();
        cboxEEstado2 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblPEDNI1 = new javax.swing.JLabel();
        lblPENomComida1 = new javax.swing.JLabel();
        cboxPEEstado1 = new javax.swing.JCheckBox();
        cboxPEEstado2 = new javax.swing.JCheckBox();
        lblPEDNI2 = new javax.swing.JLabel();
        lblPENomComida2 = new javax.swing.JLabel();
        cboxPEEstado3 = new javax.swing.JCheckBox();
        lblPEDNI3 = new javax.swing.JLabel();
        lblPENomComida3 = new javax.swing.JLabel();
        cboxPEEstado4 = new javax.swing.JCheckBox();
        lblPEDNI4 = new javax.swing.JLabel();
        lblPENomComida4 = new javax.swing.JLabel();
        cboxPEEstado5 = new javax.swing.JCheckBox();
        lblPEDNI5 = new javax.swing.JLabel();
        lblPENomComida5 = new javax.swing.JLabel();
        cboxPEEstado6 = new javax.swing.JCheckBox();
        lblPEDNI6 = new javax.swing.JLabel();
        lblPENomComida6 = new javax.swing.JLabel();
        cboxPEEstado7 = new javax.swing.JCheckBox();
        lblPEDNI7 = new javax.swing.JLabel();
        lblPENomComida7 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Pedidos entregados");

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(950, 600));
        setPreferredSize(new java.awt.Dimension(950, 600));

        jTabbedPane1.setBackground(new java.awt.Color(0, 140, 255));
        jTabbedPane1.setForeground(new java.awt.Color(102, 102, 102));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(865, 460));

        lblFoodMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/foodTemp.png"))); // NOI18N
        lblFoodMenu1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Comida 1");

        btnFoodMenu1.setBackground(new java.awt.Color(102, 102, 102));
        btnFoodMenu1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFoodMenu1.setForeground(new java.awt.Color(255, 255, 255));
        btnFoodMenu1.setText("Agregar");

        lblFoodMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/foodTemp.png"))); // NOI18N
        lblFoodMenu2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Comida 2");

        btnFoodMenu2.setBackground(new java.awt.Color(102, 102, 102));
        btnFoodMenu2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFoodMenu2.setForeground(new java.awt.Color(255, 255, 255));
        btnFoodMenu2.setText("Agregar");

        lblFoodMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/foodTemp.png"))); // NOI18N
        lblFoodMenu3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Comida 3");

        btnFoodMenu3.setBackground(new java.awt.Color(102, 102, 102));
        btnFoodMenu3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFoodMenu3.setForeground(new java.awt.Color(255, 255, 255));
        btnFoodMenu3.setText("Agregar");

        lblFoodMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/foodTemp.png"))); // NOI18N
        lblFoodMenu4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Comida 4");

        btnFoodMenu4.setBackground(new java.awt.Color(102, 102, 102));
        btnFoodMenu4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFoodMenu4.setForeground(new java.awt.Color(255, 255, 255));
        btnFoodMenu4.setText("Agregar");

        lblFoodMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/foodTemp.png"))); // NOI18N
        lblFoodMenu5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Comida 5");

        btnFoodMenu5.setBackground(new java.awt.Color(102, 102, 102));
        btnFoodMenu5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFoodMenu5.setForeground(new java.awt.Color(255, 255, 255));
        btnFoodMenu5.setText("Agregar");

        lblFoodMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/foodTemp.png"))); // NOI18N
        lblFoodMenu6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Comida 6");

        btnFoodMenu6.setBackground(new java.awt.Color(102, 102, 102));
        btnFoodMenu6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFoodMenu6.setForeground(new java.awt.Color(255, 255, 255));
        btnFoodMenu6.setText("Agregar");

        lblFoodMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/foodTemp.png"))); // NOI18N
        lblFoodMenu7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Comida 7");

        btnFoodMenu7.setBackground(new java.awt.Color(102, 102, 102));
        btnFoodMenu7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFoodMenu7.setForeground(new java.awt.Color(255, 255, 255));
        btnFoodMenu7.setText("Agregar");

        lblFoodMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/foodTemp.png"))); // NOI18N
        lblFoodMenu8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Comida 8");

        btnFoodMenu8.setBackground(new java.awt.Color(102, 102, 102));
        btnFoodMenu8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFoodMenu8.setForeground(new java.awt.Color(255, 255, 255));
        btnFoodMenu8.setText("Agregar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(lblFoodMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(lblFoodMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(lblFoodMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(lblFoodMenu4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel4)
                .addGap(133, 133, 133)
                .addComponent(jLabel5)
                .addGap(133, 133, 133)
                .addComponent(jLabel6)
                .addGap(153, 153, 153)
                .addComponent(jLabel7))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btnFoodMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(btnFoodMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(btnFoodMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(btnFoodMenu4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(lblFoodMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(lblFoodMenu6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(lblFoodMenu7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(lblFoodMenu8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel8)
                .addGap(133, 133, 133)
                .addComponent(jLabel9)
                .addGap(133, 133, 133)
                .addComponent(jLabel10)
                .addGap(153, 153, 153)
                .addComponent(jLabel11))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btnFoodMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(btnFoodMenu6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(btnFoodMenu7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(btnFoodMenu8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFoodMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoodMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoodMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoodMenu4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFoodMenu1)
                    .addComponent(btnFoodMenu2)
                    .addComponent(btnFoodMenu3)
                    .addComponent(btnFoodMenu4))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFoodMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoodMenu6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoodMenu7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoodMenu8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFoodMenu5)
                    .addComponent(btnFoodMenu6)
                    .addComponent(btnFoodMenu7)
                    .addComponent(btnFoodMenu8)))
        );

        jTabbedPane1.addTab("Menú", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Pedidos entregados");

        lblEDNI1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEDNI1.setText("DNI");
        lblEDNI1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblEDNI1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cboxEEstado1.setBackground(new java.awt.Color(255, 255, 255));
        cboxEEstado1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cboxEEstado1.setText("Estado");

        lblENomComida1.setText("Nombre Comida");

        lblEDNI2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEDNI2.setText("DNI");
        lblEDNI2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblEDNI2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblENomComida2.setText("Nombre Comida");

        cboxEEstado2.setBackground(new java.awt.Color(255, 255, 255));
        cboxEEstado2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cboxEEstado2.setText("Estado");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblEDNI1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblENomComida1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(cboxEEstado1))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblEDNI2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblENomComida2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(cboxEEstado2))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEDNI1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblENomComida1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxEEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEDNI2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblENomComida2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxEEstado2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Pedidos por entregar");

        lblPEDNI1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPEDNI1.setText("DNI");
        lblPEDNI1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblPEDNI1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblPENomComida1.setText("Nombre Comida");

        cboxPEEstado1.setBackground(new java.awt.Color(255, 255, 255));
        cboxPEEstado1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cboxPEEstado1.setText("Estado");

        cboxPEEstado2.setBackground(new java.awt.Color(255, 255, 255));
        cboxPEEstado2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cboxPEEstado2.setText("Estado");

        lblPEDNI2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPEDNI2.setText("DNI");
        lblPEDNI2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblPEDNI2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblPENomComida2.setText("Nombre Comida");

        cboxPEEstado3.setBackground(new java.awt.Color(255, 255, 255));
        cboxPEEstado3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cboxPEEstado3.setText("Estado");

        lblPEDNI3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPEDNI3.setText("DNI");
        lblPEDNI3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblPEDNI3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblPENomComida3.setText("Nombre Comida");

        cboxPEEstado4.setBackground(new java.awt.Color(255, 255, 255));
        cboxPEEstado4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cboxPEEstado4.setText("Estado");

        lblPEDNI4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPEDNI4.setText("DNI");
        lblPEDNI4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblPEDNI4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblPENomComida4.setText("Nombre Comida");

        cboxPEEstado5.setBackground(new java.awt.Color(255, 255, 255));
        cboxPEEstado5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cboxPEEstado5.setText("Estado");

        lblPEDNI5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPEDNI5.setText("DNI");
        lblPEDNI5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblPEDNI5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblPENomComida5.setText("Nombre Comida");

        cboxPEEstado6.setBackground(new java.awt.Color(255, 255, 255));
        cboxPEEstado6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cboxPEEstado6.setText("Estado");

        lblPEDNI6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPEDNI6.setText("DNI");
        lblPEDNI6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblPEDNI6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblPENomComida6.setText("Nombre Comida");

        cboxPEEstado7.setBackground(new java.awt.Color(255, 255, 255));
        cboxPEEstado7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cboxPEEstado7.setText("Estado");

        lblPEDNI7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPEDNI7.setText("DNI");
        lblPEDNI7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblPEDNI7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblPENomComida7.setText("Nombre Comida");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel3))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblPEDNI1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblPENomComida1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(cboxPEEstado1))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblPEDNI2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblPENomComida2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(cboxPEEstado2))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblPEDNI3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblPENomComida3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(cboxPEEstado3))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblPEDNI4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblPENomComida4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(cboxPEEstado4))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblPEDNI5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblPENomComida5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(cboxPEEstado5))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblPEDNI6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblPENomComida6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(cboxPEEstado6))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblPEDNI7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblPENomComida7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(cboxPEEstado7))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPEDNI1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPENomComida1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxPEEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPEDNI2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPENomComida2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxPEEstado2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPEDNI3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPENomComida3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxPEEstado3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPEDNI4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPENomComida4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxPEEstado4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPEDNI5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPENomComida5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxPEEstado5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPEDNI6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPENomComida6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxPEEstado6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPEDNI7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPENomComida7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxPEEstado7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane1.addTab("Lista de Pedidos", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFoodMenu1;
    private javax.swing.JButton btnFoodMenu2;
    private javax.swing.JButton btnFoodMenu3;
    private javax.swing.JButton btnFoodMenu4;
    private javax.swing.JButton btnFoodMenu5;
    private javax.swing.JButton btnFoodMenu6;
    private javax.swing.JButton btnFoodMenu7;
    private javax.swing.JButton btnFoodMenu8;
    private javax.swing.JCheckBox cboxEEstado1;
    private javax.swing.JCheckBox cboxEEstado2;
    private javax.swing.JCheckBox cboxPEEstado1;
    private javax.swing.JCheckBox cboxPEEstado2;
    private javax.swing.JCheckBox cboxPEEstado3;
    private javax.swing.JCheckBox cboxPEEstado4;
    private javax.swing.JCheckBox cboxPEEstado5;
    private javax.swing.JCheckBox cboxPEEstado6;
    private javax.swing.JCheckBox cboxPEEstado7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblEDNI1;
    private javax.swing.JLabel lblEDNI2;
    private javax.swing.JLabel lblENomComida1;
    private javax.swing.JLabel lblENomComida2;
    public javax.swing.JLabel lblFoodMenu1;
    private javax.swing.JLabel lblFoodMenu2;
    private javax.swing.JLabel lblFoodMenu3;
    private javax.swing.JLabel lblFoodMenu4;
    private javax.swing.JLabel lblFoodMenu5;
    private javax.swing.JLabel lblFoodMenu6;
    private javax.swing.JLabel lblFoodMenu7;
    private javax.swing.JLabel lblFoodMenu8;
    private javax.swing.JLabel lblPEDNI1;
    private javax.swing.JLabel lblPEDNI2;
    private javax.swing.JLabel lblPEDNI3;
    private javax.swing.JLabel lblPEDNI4;
    private javax.swing.JLabel lblPEDNI5;
    private javax.swing.JLabel lblPEDNI6;
    private javax.swing.JLabel lblPEDNI7;
    private javax.swing.JLabel lblPENomComida1;
    private javax.swing.JLabel lblPENomComida2;
    private javax.swing.JLabel lblPENomComida3;
    private javax.swing.JLabel lblPENomComida4;
    private javax.swing.JLabel lblPENomComida5;
    private javax.swing.JLabel lblPENomComida6;
    private javax.swing.JLabel lblPENomComida7;
    // End of variables declaration//GEN-END:variables
  public Icon setIconoButton(String direcc , JButton button){
        ImageIcon icon = new ImageIcon(getClass().getResource(direcc));
            int ancho = button.getWidth();
            int alto = button.getHeight();
            ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto,Image.SCALE_DEFAULT));
            return icono;
    }
    public Icon seticonIconPresionado(String direcc , JButton boton , int ancho , int altura){
        ImageIcon icon = new ImageIcon(getClass().getResource(direcc));
        int width = boton.getWidth()  - ancho ; 
        int heigth = boton.getHeight() - altura;
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(width, heigth, Image.SCALE_DEFAULT));
           return icono;
    }
    public Icon setScalableFoto(JLabel lbl,String direcc ){
        ImageIcon foto = new ImageIcon(getClass().getResource(direcc));
        Icon icono = new ImageIcon(foto.getImage().getScaledInstance(
                lbl.getWidth() ,
                lbl.getHeight(),
                1));
    return  icono;
    }
   
}
