/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Carlos
 */
public class menuFrm extends javax.swing.JPanel {

    /**
     * Creates new form menuFrm
     */
    public menuFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblFoodMenu1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnFoodMenu1 = new javax.swing.JButton();
        lblFoodMenu2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnFoodMenu2 = new javax.swing.JButton();
        lblFoodMenu3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnFoodMenu3 = new javax.swing.JButton();
        lblFoodMenu4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnFoodMenu4 = new javax.swing.JButton();
        lblFoodMenu5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnFoodMenu5 = new javax.swing.JButton();
        lblFoodMenu6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnFoodMenu6 = new javax.swing.JButton();
        lblFoodMenu7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnFoodMenu7 = new javax.swing.JButton();
        lblFoodMenu8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnFoodMenu8 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblEDNI1 = new javax.swing.JLabel();
        cboxEEstado1 = new javax.swing.JCheckBox();
        lblENomComida1 = new javax.swing.JLabel();
        lblEDNI2 = new javax.swing.JLabel();
        lblENomComida2 = new javax.swing.JLabel();
        cboxEEstado2 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblPEDNI1 = new javax.swing.JLabel();
        lblPENomComida1 = new javax.swing.JLabel();
        cboxPEEstado1 = new javax.swing.JCheckBox();
        cboxPEEstado2 = new javax.swing.JCheckBox();
        lblPEDNI2 = new javax.swing.JLabel();
        lblPENomComida2 = new javax.swing.JLabel();
        cboxPEEstado3 = new javax.swing.JCheckBox();
        lblPEDNI3 = new javax.swing.JLabel();
        lblPENomComida3 = new javax.swing.JLabel();
        cboxPEEstado4 = new javax.swing.JCheckBox();
        lblPEDNI4 = new javax.swing.JLabel();
        lblPENomComida4 = new javax.swing.JLabel();
        cboxPEEstado5 = new javax.swing.JCheckBox();
        lblPEDNI5 = new javax.swing.JLabel();
        lblPENomComida5 = new javax.swing.JLabel();
        cboxPEEstado6 = new javax.swing.JCheckBox();
        lblPEDNI6 = new javax.swing.JLabel();
        lblPENomComida6 = new javax.swing.JLabel();
        cboxPEEstado7 = new javax.swing.JCheckBox();
        lblPEDNI7 = new javax.swing.JLabel();
        lblPENomComida7 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Pedidos entregados");

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(950, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(0, 140, 255));
        jTabbedPane1.setForeground(new java.awt.Color(102, 102, 102));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(865, 460));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFoodMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/foodTemp.png"))); // NOI18N
        lblFoodMenu1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(lblFoodMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 100, 90));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Comida 1");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        btnFoodMenu1.setBackground(new java.awt.Color(102, 102, 102));
        btnFoodMenu1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFoodMenu1.setForeground(new java.awt.Color(255, 255, 255));
        btnFoodMenu1.setText("Agregar");
        jPanel1.add(btnFoodMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 80, -1));

        lblFoodMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/foodTemp.png"))); // NOI18N
        lblFoodMenu2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(lblFoodMenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 100, 90));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Comida 2");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        btnFoodMenu2.setBackground(new java.awt.Color(102, 102, 102));
        btnFoodMenu2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFoodMenu2.setForeground(new java.awt.Color(255, 255, 255));
        btnFoodMenu2.setText("Agregar");
        jPanel1.add(btnFoodMenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 80, -1));

        lblFoodMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/foodTemp.png"))); // NOI18N
        lblFoodMenu3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(lblFoodMenu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 100, 90));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Comida 3");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));

        btnFoodMenu3.setBackground(new java.awt.Color(102, 102, 102));
        btnFoodMenu3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFoodMenu3.setForeground(new java.awt.Color(255, 255, 255));
        btnFoodMenu3.setText("Agregar");
        jPanel1.add(btnFoodMenu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 80, -1));

        lblFoodMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/foodTemp.png"))); // NOI18N
        lblFoodMenu4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(lblFoodMenu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 100, 90));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Comida 4");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, -1, -1));

        btnFoodMenu4.setBackground(new java.awt.Color(102, 102, 102));
        btnFoodMenu4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFoodMenu4.setForeground(new java.awt.Color(255, 255, 255));
        btnFoodMenu4.setText("Agregar");
        jPanel1.add(btnFoodMenu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 80, -1));

        lblFoodMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/foodTemp.png"))); // NOI18N
        lblFoodMenu5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(lblFoodMenu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 100, 90));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Comida 5");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        btnFoodMenu5.setBackground(new java.awt.Color(102, 102, 102));
        btnFoodMenu5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFoodMenu5.setForeground(new java.awt.Color(255, 255, 255));
        btnFoodMenu5.setText("Agregar");
        jPanel1.add(btnFoodMenu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 80, -1));

        lblFoodMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/foodTemp.png"))); // NOI18N
        lblFoodMenu6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(lblFoodMenu6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 100, 90));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Comida 6");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, -1, -1));

        btnFoodMenu6.setBackground(new java.awt.Color(102, 102, 102));
        btnFoodMenu6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFoodMenu6.setForeground(new java.awt.Color(255, 255, 255));
        btnFoodMenu6.setText("Agregar");
        jPanel1.add(btnFoodMenu6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 80, -1));

        lblFoodMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/foodTemp.png"))); // NOI18N
        lblFoodMenu7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(lblFoodMenu7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 100, 90));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Comida 7");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, -1, -1));

        btnFoodMenu7.setBackground(new java.awt.Color(102, 102, 102));
        btnFoodMenu7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFoodMenu7.setForeground(new java.awt.Color(255, 255, 255));
        btnFoodMenu7.setText("Agregar");
        jPanel1.add(btnFoodMenu7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, 80, -1));

        lblFoodMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/foodTemp.png"))); // NOI18N
        lblFoodMenu8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(lblFoodMenu8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, 100, 90));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Comida 8");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, -1, -1));

        btnFoodMenu8.setBackground(new java.awt.Color(102, 102, 102));
        btnFoodMenu8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFoodMenu8.setForeground(new java.awt.Color(255, 255, 255));
        btnFoodMenu8.setText("Agregar");
        jPanel1.add(btnFoodMenu8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, 80, -1));

        jTabbedPane1.addTab("Menú", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Pedidos entregados");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, 20));

        lblEDNI1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEDNI1.setText("DNI");
        lblEDNI1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblEDNI1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(lblEDNI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 100, 20));

        cboxEEstado1.setBackground(new java.awt.Color(255, 255, 255));
        cboxEEstado1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cboxEEstado1.setText("Estado");
        jPanel4.add(cboxEEstado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, 20));

        lblENomComida1.setText("Nombre Comida");
        jPanel4.add(lblENomComida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 150, 20));

        lblEDNI2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEDNI2.setText("DNI");
        lblEDNI2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblEDNI2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(lblEDNI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, 20));

        lblENomComida2.setText("Nombre Comida");
        jPanel4.add(lblENomComida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 150, 20));

        cboxEEstado2.setBackground(new java.awt.Color(255, 255, 255));
        cboxEEstado2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cboxEEstado2.setText("Estado");
        jPanel4.add(cboxEEstado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, 20));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 400, 410));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Pedidos por entregar");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, 20));

        lblPEDNI1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPEDNI1.setText("DNI");
        lblPEDNI1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblPEDNI1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(lblPEDNI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, 20));

        lblPENomComida1.setText("Nombre Comida");
        jPanel3.add(lblPENomComida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 150, 20));

        cboxPEEstado1.setBackground(new java.awt.Color(255, 255, 255));
        cboxPEEstado1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cboxPEEstado1.setText("Estado");
        jPanel3.add(cboxPEEstado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, 20));

        cboxPEEstado2.setBackground(new java.awt.Color(255, 255, 255));
        cboxPEEstado2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cboxPEEstado2.setText("Estado");
        jPanel3.add(cboxPEEstado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, 20));

        lblPEDNI2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPEDNI2.setText("DNI");
        lblPEDNI2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblPEDNI2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(lblPEDNI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 100, 20));

        lblPENomComida2.setText("Nombre Comida");
        jPanel3.add(lblPENomComida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 150, 20));

        cboxPEEstado3.setBackground(new java.awt.Color(255, 255, 255));
        cboxPEEstado3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cboxPEEstado3.setText("Estado");
        jPanel3.add(cboxPEEstado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, 20));

        lblPEDNI3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPEDNI3.setText("DNI");
        lblPEDNI3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblPEDNI3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(lblPEDNI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, 20));

        lblPENomComida3.setText("Nombre Comida");
        jPanel3.add(lblPENomComida3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 150, 20));

        cboxPEEstado4.setBackground(new java.awt.Color(255, 255, 255));
        cboxPEEstado4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cboxPEEstado4.setText("Estado");
        jPanel3.add(cboxPEEstado4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, 20));

        lblPEDNI4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPEDNI4.setText("DNI");
        lblPEDNI4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblPEDNI4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(lblPEDNI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 100, 20));

        lblPENomComida4.setText("Nombre Comida");
        jPanel3.add(lblPENomComida4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 150, 20));

        cboxPEEstado5.setBackground(new java.awt.Color(255, 255, 255));
        cboxPEEstado5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cboxPEEstado5.setText("Estado");
        jPanel3.add(cboxPEEstado5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, 20));

        lblPEDNI5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPEDNI5.setText("DNI");
        lblPEDNI5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblPEDNI5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(lblPEDNI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 100, 20));

        lblPENomComida5.setText("Nombre Comida");
        jPanel3.add(lblPENomComida5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 150, 20));

        cboxPEEstado6.setBackground(new java.awt.Color(255, 255, 255));
        cboxPEEstado6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cboxPEEstado6.setText("Estado");
        jPanel3.add(cboxPEEstado6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, -1, 20));

        lblPEDNI6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPEDNI6.setText("DNI");
        lblPEDNI6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblPEDNI6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(lblPEDNI6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 100, 20));

        lblPENomComida6.setText("Nombre Comida");
        jPanel3.add(lblPENomComida6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 150, 20));

        cboxPEEstado7.setBackground(new java.awt.Color(255, 255, 255));
        cboxPEEstado7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cboxPEEstado7.setText("Estado");
        jPanel3.add(cboxPEEstado7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, 20));

        lblPEDNI7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPEDNI7.setText("DNI");
        lblPEDNI7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblPEDNI7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(lblPEDNI7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 100, 20));

        lblPENomComida7.setText("Nombre Comida");
        jPanel3.add(lblPENomComida7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 150, 20));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 410, 410));

        jTabbedPane1.addTab("Lista de Pedidos", jPanel2);

        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 37, -1, 530));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFoodMenu1;
    private javax.swing.JButton btnFoodMenu2;
    private javax.swing.JButton btnFoodMenu3;
    private javax.swing.JButton btnFoodMenu4;
    private javax.swing.JButton btnFoodMenu5;
    private javax.swing.JButton btnFoodMenu6;
    private javax.swing.JButton btnFoodMenu7;
    private javax.swing.JButton btnFoodMenu8;
    private javax.swing.JCheckBox cboxEEstado1;
    private javax.swing.JCheckBox cboxEEstado2;
    private javax.swing.JCheckBox cboxPEEstado1;
    private javax.swing.JCheckBox cboxPEEstado2;
    private javax.swing.JCheckBox cboxPEEstado3;
    private javax.swing.JCheckBox cboxPEEstado4;
    private javax.swing.JCheckBox cboxPEEstado5;
    private javax.swing.JCheckBox cboxPEEstado6;
    private javax.swing.JCheckBox cboxPEEstado7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblEDNI1;
    private javax.swing.JLabel lblEDNI2;
    private javax.swing.JLabel lblENomComida1;
    private javax.swing.JLabel lblENomComida2;
    private javax.swing.JLabel lblFoodMenu1;
    private javax.swing.JLabel lblFoodMenu2;
    private javax.swing.JLabel lblFoodMenu3;
    private javax.swing.JLabel lblFoodMenu4;
    private javax.swing.JLabel lblFoodMenu5;
    private javax.swing.JLabel lblFoodMenu6;
    private javax.swing.JLabel lblFoodMenu7;
    private javax.swing.JLabel lblFoodMenu8;
    private javax.swing.JLabel lblPEDNI1;
    private javax.swing.JLabel lblPEDNI2;
    private javax.swing.JLabel lblPEDNI3;
    private javax.swing.JLabel lblPEDNI4;
    private javax.swing.JLabel lblPEDNI5;
    private javax.swing.JLabel lblPEDNI6;
    private javax.swing.JLabel lblPEDNI7;
    private javax.swing.JLabel lblPENomComida1;
    private javax.swing.JLabel lblPENomComida2;
    private javax.swing.JLabel lblPENomComida3;
    private javax.swing.JLabel lblPENomComida4;
    private javax.swing.JLabel lblPENomComida5;
    private javax.swing.JLabel lblPENomComida6;
    private javax.swing.JLabel lblPENomComida7;
    // End of variables declaration//GEN-END:variables
}
