/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorMenu;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.ImageObserver;
import java.awt.image.ImageProducer;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.Comida;
import modelo.ImageConfig;
import modelo.ListaPedido;
import modelo.Menu;
import modelo.Pedido;
import sam.SAM;

/**
 *
 * @author Carlos
 */

public class PanelMenu extends javax.swing.JPanel {

    /**
     * Creates new form menuFrm
     */
    

    PanelDatos panDatos = new PanelDatos();

    Menu miMenu = Menu.getMenu();
    ListaPedido misPedidos = ListaPedido.getListaPedido();
    public PanelMenu() {
        initComponents();
      
          
     miMenu.setLlenarComidas(miMenu);
        
     panDatos.btnCerrar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                panDatos.dispose();
            }
     });
     panDatos.btnAceptar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
        Cliente cliente = new Cliente(panDatos.txtNombre.getText(),panDatos.txtDni.getText() );
        float precio = Float.parseFloat(panDatos.lblPrecio.getText());
        Comida comida = new Comida(panDatos.lblNombreComida.getText(), precio);
        
        misPedidos.addPedido(comida, cliente);
        
                System.out.println(misPedidos.size());
        
        /*
        
        Pedido pedido = new Pedido(comida, cliente);
        listaPedidos.add(pedido);
        */
        mostrar();
        panDatos.txtDni.setText("");
        panDatos.txtNombre.setText("");
        panDatos.dispose();
            }
     
     });
     
   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblFoodMenu1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnFoodMenu1 = new javax.swing.JButton();
        lblFoodMenu2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblFoodMenu3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnFoodMenu3 = new javax.swing.JButton();
        lblFoodMenu4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnFoodMenu4 = new javax.swing.JButton();
        lblFoodMenu5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnFoodMenu5 = new javax.swing.JButton();
        lblFoodMenu6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnFoodMenu6 = new javax.swing.JButton();
        lblFoodMenu7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnFoodMenu7 = new javax.swing.JButton();
        lblFoodMenu8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnFoodMenu8 = new javax.swing.JButton();
        btnFoodMenu2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableReceveid = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableSend = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Pedidos entregados");

        setBackground(new java.awt.Color(180, 237, 131));
        setMinimumSize(new java.awt.Dimension(950, 500));
        setPreferredSize(new java.awt.Dimension(950, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(0, 140, 255));
        jTabbedPane1.setForeground(new java.awt.Color(102, 102, 102));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(865, 460));

        lblFoodMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arrayComida/comida1.jpg"))); // NOI18N
        lblFoodMenu1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Lomo Saltado");

        btnFoodMenu1.setBackground(new java.awt.Color(102, 102, 102));
        btnFoodMenu1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFoodMenu1.setForeground(new java.awt.Color(255, 255, 255));
        btnFoodMenu1.setText("Agregar");
        btnFoodMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoodMenu1ActionPerformed(evt);
            }
        });

        lblFoodMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arrayComida/comida2.jpg"))); // NOI18N
        lblFoodMenu2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Aji de Gallina");

        lblFoodMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/foodTemp.png"))); // NOI18N
        lblFoodMenu3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Arroz con pollo");

        btnFoodMenu3.setBackground(new java.awt.Color(102, 102, 102));
        btnFoodMenu3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFoodMenu3.setForeground(new java.awt.Color(255, 255, 255));
        btnFoodMenu3.setText("Agregar");

        lblFoodMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/foodTemp.png"))); // NOI18N
        lblFoodMenu4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Sopa Seca");

        btnFoodMenu4.setBackground(new java.awt.Color(102, 102, 102));
        btnFoodMenu4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFoodMenu4.setForeground(new java.awt.Color(255, 255, 255));
        btnFoodMenu4.setText("Agregar");

        lblFoodMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/foodTemp.png"))); // NOI18N
        lblFoodMenu5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Comida 5");

        btnFoodMenu5.setBackground(new java.awt.Color(102, 102, 102));
        btnFoodMenu5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFoodMenu5.setForeground(new java.awt.Color(255, 255, 255));
        btnFoodMenu5.setText("Agregar");

        lblFoodMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/foodTemp.png"))); // NOI18N
        lblFoodMenu6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Comida 6");

        btnFoodMenu6.setBackground(new java.awt.Color(102, 102, 102));
        btnFoodMenu6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFoodMenu6.setForeground(new java.awt.Color(255, 255, 255));
        btnFoodMenu6.setText("Agregar");

        lblFoodMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/foodTemp.png"))); // NOI18N
        lblFoodMenu7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Comida 7");

        btnFoodMenu7.setBackground(new java.awt.Color(102, 102, 102));
        btnFoodMenu7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFoodMenu7.setForeground(new java.awt.Color(255, 255, 255));
        btnFoodMenu7.setText("Agregar");

        lblFoodMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/foodTemp.png"))); // NOI18N
        lblFoodMenu8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Comida 8");

        btnFoodMenu8.setBackground(new java.awt.Color(102, 102, 102));
        btnFoodMenu8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFoodMenu8.setForeground(new java.awt.Color(255, 255, 255));
        btnFoodMenu8.setText("Agregar");

        btnFoodMenu2.setBackground(new java.awt.Color(102, 102, 102));
        btnFoodMenu2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFoodMenu2.setForeground(new java.awt.Color(255, 255, 255));
        btnFoodMenu2.setText("Agregar");
        btnFoodMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoodMenu2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel8)
                        .addGap(133, 133, 133)
                        .addComponent(jLabel9)
                        .addGap(133, 133, 133)
                        .addComponent(jLabel10)
                        .addGap(153, 153, 153)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnFoodMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(btnFoodMenu6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(btnFoodMenu7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addComponent(btnFoodMenu8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFoodMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(105, 105, 105)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(331, 331, 331)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnFoodMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110)
                                .addComponent(btnFoodMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(130, 130, 130)
                                .addComponent(btnFoodMenu4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblFoodMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(lblFoodMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(lblFoodMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(110, 110, 110)
                        .addComponent(lblFoodMenu4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lblFoodMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(lblFoodMenu6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(lblFoodMenu7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(lblFoodMenu8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFoodMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoodMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoodMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoodMenu4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFoodMenu1)
                            .addComponent(btnFoodMenu3)
                            .addComponent(btnFoodMenu4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnFoodMenu2)))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFoodMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoodMenu6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoodMenu7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoodMenu8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFoodMenu5)
                    .addComponent(btnFoodMenu6)
                    .addComponent(btnFoodMenu7)
                    .addComponent(btnFoodMenu8)))
        );

        jTabbedPane1.addTab("Menú", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        TableReceveid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "comida", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableReceveid.setColumnSelectionAllowed(true);
        TableReceveid.setDoubleBuffered(true);
        TableReceveid.setRowHeight(20);
        jScrollPane2.setViewportView(TableReceveid);

        TableSend.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Comida", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableSend.setRowHeight(20);
        jScrollPane1.setViewportView(TableSend);

        jLabel1.setText("Lista de Pedidos");

        jLabel3.setText("Pedidos Entregados");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lista de Pedidos", jPanel2);

        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 940, 450));
    }// </editor-fold>//GEN-END:initComponents
  
    private void btnFoodMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoodMenu1ActionPerformed
   panDatos.setVisible(true);
   panDatos.lblNombreComida.setText(miMenu.getComidaNombreI(0));    
    panDatos.lblFotos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arrayComida/comida1.jpg")));
    panDatos.lblPrecio.setText(String.valueOf(miMenu.getComidaPrecioI(0)));
    
 
    
    
    }//GEN-LAST:event_btnFoodMenu1ActionPerformed

    private void btnFoodMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoodMenu2ActionPerformed
        
  panDatos.setVisible(true);
   panDatos.lblNombreComida.setText(miMenu.getComidaNombreI(1));    
    panDatos.lblFotos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arrayComida/comida2.jpg")));
    panDatos.lblPrecio.setText(String.valueOf(miMenu.getComidaPrecioI(1)));
        
        
        
    }//GEN-LAST:event_btnFoodMenu2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable TableReceveid;
    public javax.swing.JTable TableSend;
    public javax.swing.JButton btnFoodMenu1;
    private javax.swing.JButton btnFoodMenu2;
    private javax.swing.JButton btnFoodMenu3;
    private javax.swing.JButton btnFoodMenu4;
    private javax.swing.JButton btnFoodMenu5;
    private javax.swing.JButton btnFoodMenu6;
    private javax.swing.JButton btnFoodMenu7;
    private javax.swing.JButton btnFoodMenu8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JLabel lblFoodMenu1;
    public javax.swing.JLabel lblFoodMenu2;
    public javax.swing.JLabel lblFoodMenu3;
    public javax.swing.JLabel lblFoodMenu4;
    public javax.swing.JLabel lblFoodMenu5;
    public javax.swing.JLabel lblFoodMenu6;
    public javax.swing.JLabel lblFoodMenu7;
    public javax.swing.JLabel lblFoodMenu8;
    // End of variables declaration//GEN-END:variables
      public void mostrar() {
  
        Object matriz[][] = new Object[misPedidos.size()][4];
        String[] columnas = {"DNI", "Nombre", "comida", "Estado"};
        for (int i = 0; i < misPedidos.size(); i++) {
            matriz[i][0] = misPedidos.buscar(i).getPedidoDniCliente();
          matriz[i][1] = misPedidos.buscar(i).getPedidoClienteNombre();
            matriz[i][2] = misPedidos.buscar(i).getPeidoNombreComida();
            matriz[i][3] = misPedidos.buscar(i).isEstado();
        }
      
        TableReceveid.setModel(new javax.swing.table.DefaultTableModel(
           matriz,
           columnas
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableReceveid.setColumnSelectionAllowed(true);
        TableReceveid.setDoubleBuffered(true);
        TableReceveid.setRowHeight(25);
        jScrollPane2.setViewportView(TableReceveid);
      }
    public Icon setIconoButton(String direcc, JButton button) {
        ImageIcon icon = new ImageIcon(getClass().getResource(direcc));
        int ancho = button.getWidth();
        int alto = button.getHeight();
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        return icono;
    }

    public Icon seticonIconPresionado(String direcc, JButton boton, int ancho, int altura) {
        ImageIcon icon = new ImageIcon(getClass().getResource(direcc));
        int width = boton.getWidth() - ancho;
        int heigth = boton.getHeight() - altura;
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(width, heigth, Image.SCALE_DEFAULT));
        return icono;
    }

    public Icon setScalableFoto(JLabel lbl, String direcc) {
        ImageIcon foto = new ImageIcon(getClass().getResource(direcc));
        Icon icono = new ImageIcon(foto.getImage().getScaledInstance(
                lbl.getWidth(),
                lbl.getHeight(),
                1));
        return icono;
    }


}
