/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Icon;

/**
 *
 * @author anthony.ricse
 */
public class VentanaPrincipal extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form principal
     */
    PanelIngredientes panel1 = new PanelIngredientes();
    PanelHome panelPrincipal = new PanelHome();
    private Icon icono;

    public VentanaPrincipal() {
        initComponents();

        /*imagenTableTextPanel1*/
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panContenedor = new javax.swing.JPanel();
        panBtns = new javax.swing.JPanel();
        btnIngre = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnBalance = new javax.swing.JButton();
        lblBotonoes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panContenedor.setMinimumSize(new java.awt.Dimension(950, 600));
        panContenedor.setPreferredSize(new java.awt.Dimension(950, 600));
        panContenedor.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panContenedor, java.awt.BorderLayout.CENTER);

        panBtns.setBackground(new java.awt.Color(51, 102, 0));
        panBtns.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIngre.setMinimumSize(new java.awt.Dimension(100, 100));
        btnIngre.setPreferredSize(new java.awt.Dimension(100, 100));
        btnIngre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngreActionPerformed(evt);
            }
        });
        panBtns.add(btnIngre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));
        panBtns.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 110, 100));
        panBtns.add(btnBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 110, 100));
        panBtns.add(lblBotonoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 110));

        getContentPane().add(panBtns, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngreActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBalance;
    public javax.swing.JButton btnIngre;
    public javax.swing.JButton btnMenu;
    public javax.swing.JLabel lblBotonoes;
    public javax.swing.JPanel panBtns;
    public javax.swing.JPanel panContenedor;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent arg0) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
