/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import  java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author anthony.ricse
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private int xx,xy;
    
    public VentanaPrincipal() {
        this.setUndecorated(true);
        initComponents();
        this.btnExit.setIcon(setScalableFoto(this.btnExit, "/imagenes/paneButton.jpg"));
        this.setLocationRelativeTo(null);
        

    }
        public Image getIconImage(){
            Image Logo = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/logo.png"));
             return Logo;
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panContenedor = new javax.swing.JPanel();
        panBtns = new javax.swing.JPanel();
        btnInventario = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnBalance = new javax.swing.JButton();
        ExitBTN = new javax.swing.JButton();
        btnExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(950, 600));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panContenedor.setMinimumSize(new java.awt.Dimension(950, 490));
        panContenedor.setPreferredSize(new java.awt.Dimension(950, 490));
        panContenedor.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 500));

        panBtns.setBackground(new java.awt.Color(51, 102, 0));
        panBtns.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inventaryBtn.PNG"))); // NOI18N
        btnInventario.setMinimumSize(new java.awt.Dimension(100, 100));
        btnInventario.setPreferredSize(new java.awt.Dimension(100, 100));
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        panBtns.add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 80, 80));

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MenuBtn.png"))); // NOI18N
        panBtns.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 80, 80));

        btnBalance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/DineroBtn.PNG"))); // NOI18N
        panBtns.add(btnBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 80, 80));

        ExitBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exitMain.PNG"))); // NOI18N
        ExitBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ExitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBTNActionPerformed(evt);
            }
        });
        panBtns.add(ExitBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 70, 70));

        btnExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btnExitMouseDragged(evt);
            }
        });
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnExitMousePressed(evt);
            }
        });
        panBtns.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 100));

        getContentPane().add(panBtns, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 950, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void ExitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBTNActionPerformed
    System.exit(0);    }//GEN-LAST:event_ExitBTNActionPerformed

    private void btnExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_btnExitMousePressed

    private void btnExitMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x-xx, y-xy-500);
    }//GEN-LAST:event_btnExitMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
//        xx = evt.getX();
//        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
//        int x = evt.getXOnScreen();
//        int y = evt.getYOnScreen();
//        
//        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_formMouseDragged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitBTN;
    public javax.swing.JButton btnBalance;
    public javax.swing.JLabel btnExit;
    public javax.swing.JButton btnInventario;
    public javax.swing.JButton btnMenu;
    public javax.swing.JPanel panBtns;
    public javax.swing.JPanel panContenedor;
    // End of variables declaration//GEN-END:variables

    public Icon setScalableFoto(JLabel lbl, String direcc) {
        ImageIcon foto = new ImageIcon(getClass().getResource(direcc));
        Icon icono = new ImageIcon(foto.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(), 1));
        return icono;
    }
}
